import * as fs from "node:fs";
import * as path from "node:path";
import { createHash } from "node:crypto";
import { CWF_DIRS, CWF_ENTRY_FILE } from "../types";
import { legacyClaudeSources } from "../fs-loader";
import { parseFrontmatter } from "../parse";

// Claude projector: materializes a CWF workspace into the `.claude/` convention
// (+ CLAUDE.md) so Claude Code's native machinery — slash commands, subagents,
// skills — executes our provider-neutral source. `.claude/` is a BUILD ARTIFACT
// (like dist/): regenerable, hash-skipped, never the source of truth.
//
// Ownership rules: the projector manages CLAUDE.md and *.md files inside
// .claude/{commands,agents,skills,templates} ONLY. It never touches
// settings.local.json (Concourse hook config) or anything else.
//
// Note on layering: this maps files to a vendor CONVENTION but imports no vendor
// SDK — it's pure file mapping, kept beside the domain loader so both the server
// process and the electron main process can call it.

const MANIFEST = "concourse-projection.json";
const SENTINEL = "<!-- GENERATED by Concourse from workspace.md — edits here are overwritten. Edit the workspace files instead. -->";

const PROJECTED_DIRS = [
  CWF_DIRS.command,
  CWF_DIRS.agent,
  CWF_DIRS.skill,
  CWF_DIRS.template,
] as const;

type Manifest = { hash: string; ownedFiles: string[] };

function sourceHash(dir: string): string {
  const h = createHash("sha1");
  const add = (p: string) => {
    try {
      const st = fs.statSync(p);
      h.update(`${p}|${st.size}|${st.mtimeMs};`);
    } catch {
      /* missing */
    }
  };
  add(path.join(dir, CWF_ENTRY_FILE));
  for (const sub of PROJECTED_DIRS) {
    const abs = path.join(dir, sub);
    let files: string[] = [];
    try {
      files = fs.readdirSync(abs).filter((f) => f.endsWith(".md")).sort();
    } catch {
      /* absent dir */
    }
    for (const f of files) add(path.join(abs, f));
  }
  // User-authored legacy .claude commands feed .opencode/command too — edits
  // and deletions there must invalidate the projection.
  for (const f of legacyClaudeSources(dir, CWF_DIRS.command)) {
    add(path.join(dir, ".claude", CWF_DIRS.command, f));
  }
  return h.digest("hex");
}

function readManifest(claudeDir: string): Manifest | null {
  try {
    const raw = fs.readFileSync(path.join(claudeDir, MANIFEST), "utf8");
    const parsed = JSON.parse(raw) as Manifest;
    return typeof parsed?.hash === "string" && Array.isArray(parsed?.ownedFiles) ? parsed : null;
  } catch {
    return null;
  }
}

function hasCwfContent(dir: string): boolean {
  for (const sub of PROJECTED_DIRS) {
    try {
      if (fs.readdirSync(path.join(dir, sub)).some((f) => f.endsWith(".md"))) return true;
    } catch {
      /* dir absent */
    }
  }
  return legacyClaudeSources(dir, CWF_DIRS.command).length > 0;
}

/** Project CWF sources into the vendor conventions. Full workspaces (with
 *  workspace.md) also get CLAUDE.md/AGENTS.md; a classic repo with CWF content
 *  dirs gets ONLY the command/agent/skill/template fan-out — its own
 *  CLAUDE.md/AGENTS.md are never touched. No-op when there is nothing to
 *  project; hash-skipped when sources are unchanged. Returns whether a
 *  (re)projection ran. */
export function projectClaudeWorkspace(dir: string): boolean {
  const entry = path.join(dir, CWF_ENTRY_FILE);
  const hasEntry = fs.existsSync(entry);
  if (!hasEntry && !hasCwfContent(dir)) return false;

  const claudeDir = path.join(dir, ".claude");
  const hash = sourceHash(dir);
  const previous = readManifest(claudeDir);
  if (previous?.hash === hash) return false;

  const owned: string[] = [];
  fs.mkdirSync(claudeDir, { recursive: true });

  if (hasEntry) {
    // CLAUDE.md ← workspace.md body (frontmatter stripped; Claude doesn't need it).
    const { body } = parseFrontmatter(fs.readFileSync(entry, "utf8"));
    fs.writeFileSync(path.join(dir, "CLAUDE.md"), `${SENTINEL}\n\n${body.trimStart()}`, "utf8");
    owned.push("CLAUDE.md");

    // AGENTS.md — the cross-vendor convention (OpenCode, Codex, Cursor all read
    // it). Same content as CLAUDE.md: one source, N projections (plan §M6).
    fs.writeFileSync(path.join(dir, "AGENTS.md"), `${SENTINEL}\n\n${body.trimStart()}`, "utf8");
    owned.push("AGENTS.md");
  }

  // OpenCode slash commands: .opencode/command/*.md ← commands/*.md plus
  // user-authored legacy .claude/commands (root wins on name collisions), so a
  // classic repo's commands work on OpenCode too. Verbatim copies — OpenCode
  // tolerates unknown frontmatter keys the same way Claude does.
  let rootCmdFiles: string[] = [];
  try {
    rootCmdFiles = fs.readdirSync(path.join(dir, "commands")).filter((f) => f.endsWith(".md"));
  } catch {
    /* commands dir absent */
  }
  const rootCmdSet = new Set(rootCmdFiles);
  const legacyCmdFiles = legacyClaudeSources(dir, CWF_DIRS.command).filter(
    (f) => !rootCmdSet.has(f),
  );
  if (rootCmdFiles.length + legacyCmdFiles.length > 0) {
    const ocDir = path.join(dir, ".opencode", "command");
    fs.mkdirSync(ocDir, { recursive: true });
    for (const f of rootCmdFiles) {
      fs.copyFileSync(path.join(dir, "commands", f), path.join(ocDir, f));
      owned.push(path.join(".opencode", "command", f));
    }
    for (const f of legacyCmdFiles) {
      fs.copyFileSync(path.join(dir, ".claude", CWF_DIRS.command, f), path.join(ocDir, f));
      owned.push(path.join(".opencode", "command", f));
    }
  }
  // Remove previously-projected .opencode copies whose source is gone.
  {
    const currentSet = new Set(
      [...rootCmdFiles, ...legacyCmdFiles].map((f) => path.join(".opencode", "command", f)),
    );
    for (const prev of previous?.ownedFiles ?? []) {
      if (prev.startsWith(path.join(".opencode", "command") + path.sep) && !currentSet.has(prev)) {
        try {
          fs.rmSync(path.join(dir, prev), { force: true });
        } catch {
          /* best-effort */
        }
      }
    }
  }

  for (const sub of PROJECTED_DIRS) {
    const srcDir = path.join(dir, sub);
    const dstDir = path.join(claudeDir, sub);
    let files: string[] = [];
    try {
      files = fs.readdirSync(srcDir).filter((f) => f.endsWith(".md"));
    } catch {
      /* dir absent — nothing to project */
    }
    if (files.length > 0) fs.mkdirSync(dstDir, { recursive: true });
    for (const f of files) {
      // Verbatim copy: Claude tolerates our extra frontmatter keys (custom/owns/…).
      fs.copyFileSync(path.join(srcDir, f), path.join(dstDir, f));
      owned.push(path.join(".claude", sub, f));
    }
    // Remove previously-projected files whose source is gone (deletes propagate).
    const currentSet = new Set(files.map((f) => path.join(".claude", sub, f)));
    for (const prev of previous?.ownedFiles ?? []) {
      if (prev.startsWith(path.join(".claude", sub) + path.sep) && !currentSet.has(prev)) {
        try {
          fs.rmSync(path.join(dir, prev), { force: true });
        } catch {
          /* best-effort */
        }
      }
    }
  }

  fs.writeFileSync(
    path.join(claudeDir, MANIFEST),
    JSON.stringify({ hash, ownedFiles: owned }, null, 2),
    "utf8",
  );
  return true;
}
